# Generated by Django 4.1.3 on 2022-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_id",
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
